# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85109e895c67cc1fa54b3560813dc2c93cb875e2c90e811999725b73226c9c5760479aa0b3467c790eb21b4720e6df3ea506216cf4b99b1f4aafd80db2f1f5d9

test:
  secret_key_base: 285cbd56a8aa6205f6df5e8f2c43604e4a64a3fd6c413a36b54dcdf7f5c0c462def7bb6bf2950753cf0ee4085f2891649a9a981a339fd3991e80a01735236192

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
